language: php
services:
  - mysql
  - mongodb

test:
  adapter: mysql
  database: laravelTesting
  username: root


php:
    7.2
    7.2.15

install:
  composer install

script: vendor/phpunit/phpunit/phpunit
