language: php
services:
  - mysql
  - mongodb

test:
  adapter: mysql
  database: laravelTesting
  username: travis



php:
    7.2
    7.2.15

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS laravelTesting; USE laravelTesting';

install:
  composer install

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --prefer-source --no-interaction --no-suggest
  - cp .env.testing .env
  - php artisan key:generate
  - php artisan migrate
  - php artisan passport:keys

script: vendor/phpunit/phpunit/phpunit
